- name: this playbook is for pulling ECR Image and starting docker container
  hosts: docker
  become: true
  
  tasks:
    -  name: login to ECR
       command: 'aws ecr get-login --no-include-email'
       
    -  name: pull images
       command: 'docker pull 587589636093.dkr.ecr.us-east-1.amazonaws.com/nginx:1'
                            
    -  name: start docker container
       command: 'docker run --name myng7 -itd -p 87:80 587589636093.dkr.ecr.us-east-1.amazonaws.com/nginx:1'
